# Generated by Django 4.2.10 on 2024-02-24 21:53

from django.db import migrations

def seed_counties_and_subcounties(apps, schema_editor):
    County = apps.get_model('api', 'County')
    SubCounty = apps.get_model('api', 'SubCounty')

    data = [
        {'county_name': 'Baringo', 'subcounties': ['Baringo Central', 'Baringo North', 'Baringo South', 'Eldama Ravine', 'Mogotio', 'Tiaty']},
        {'county_name': 'Bomet', 'subcounties': ['Bomet Central', 'Bomet East', 'Chepalungu', 'Konoin', 'Sotik']},
        {'county_name': 'Bungoma', 'subcounties': ['Bumula', 'Kabuchai', 'Kanduyi', 'Kimilil', 'Mt Elgon', 'Sirisia', 'Tongaren', 'Webuye East', 'Webuye West']},
        {'county_name': 'Busia', 'subcounties': ['Budalangi', 'Butula', 'Funyula', 'Nambele', 'Teso North', 'Teso South']},
        {'county_name': 'Elgeyo-Marakwet', 'subcounties': ['Keiyo North', 'Keiyo South', 'Marakwet East', 'Marakwet West']},
        {'county_name': 'Embu', 'subcounties': ['Manyatta', 'Mbeere North', 'Mbeere South', 'Runyenjes']},
        {'county_name': 'Garissa', 'subcounties': ['Daadab', 'Fafi', 'Garissa Township', 'Hulugho', 'Ijara', 'Lagdera', 'Balambala']},
        {'county_name': 'Homa Bay', 'subcounties': ['Homabay Town', 'Kabondo', 'Karachwonyo', 'Kasipul', 'Mbita', 'Ndhiwa', 'Rangwe', 'Suba']},
        {'county_name': 'Isiolo', 'subcounties': ['Isiolo', 'Merti', 'Garbatulla']},
        {'county_name': 'Kajiado', 'subcounties': ['Isinya', 'Kajiado Central', 'Kajiado North', 'Loitokitok', 'Mashuuru']},
        {'county_name': 'Kakamega', 'subcounties': ['Butere', 'Kakamega Central', 'Kakamega East', 'Kakamega North', 'Kakamega South', 'Khwisero', 'Lugari', 'Lukuyani', 'Lurambi', 'Matete', 'Mumias', 'Mutungu', 'Navakholo']},
        {'county_name': 'Kericho', 'subcounties': ['Ainamoi', 'Belgut', 'Bureti', 'Kipkelion East', 'Kipkelion West', 'Soin/Sigowet']},
        {'county_name': 'Kiambu', 'subcounties': ['Gatundu North', 'Gatundu South', 'Githunguri', 'Juja', 'Kabete', 'Kiambaa', 'Kiambu', 'Kikuyu', 'Limuru', 'Ruiru', 'Thika Town', 'Lari']},
        {'county_name': 'Kilifi', 'subcounties': ['Ganze', 'Kaloleni', 'Kilifi North', 'Kilifi South', 'Magarini', 'Malindi', 'Rabai']},
        {'county_name': 'Kirinyaga', 'subcounties': ['Kirinyaga Central', 'Kirinyaga East', 'Kirinyaga West', 'Mwea East', 'Mwea West']},
        {'county_name': 'Kisii', 'subcounties': []},  # No subcounties provided
        {'county_name': 'Kisumu', 'subcounties': ['Kisumu Central', 'Kisumu East', 'Kisumu West', 'Muhoroni', 'Nyakach', 'Nyando', 'Seme']},
        {'county_name': 'Kitui', 'subcounties': ['Kitui West', 'Kitui Central', 'Kitui Rural', 'Kitui South', 'Kitui East', 'Mwingi North', 'Mwingi West', 'Mwingi Central']},
        {'county_name': 'Kwale', 'subcounties': ['Kinango', 'Lunga Lunga', 'Msambweni', 'Matuga']},
        {'county_name': 'Laikipia', 'subcounties': ['Laikipia Central', 'Laikipia East', 'Laikipia North', 'Laikipia West', 'Nyahururu']},
        {'county_name': 'Lamu', 'subcounties': ['Lamu East', 'Lamu West']},
        {'county_name': 'Machakos', 'subcounties': ['Kathiani', 'Machakos Town', 'Masinga', 'Matungulu', 'Mavoko', 'Mwala', 'Yatta']},
        {'county_name': 'Makueni', 'subcounties': ['Kaiti', 'Kibwezi West', 'Kibwezi East', 'Kilome', 'Makueni', 'Mbooni']},
        {'county_name': 'Mandera', 'subcounties': ['Banissa', 'Lafey', 'Mandera East', 'Mandera North', 'Mandera South', 'Mandera West']},
        {'county_name': 'Marsabit', 'subcounties': ['Laisamis', 'Moyale', 'North Hor', 'Saku']},
        {'county_name': 'Meru', 'subcounties': ['Buuri', 'Igembe Central', 'Igembe North', 'Igembe South', 'Imenti Central', 'Imenti North', 'Imenti South', 'Tigania East', 'Tigania West']},
        {'county_name': 'Migori', 'subcounties': ['Awendo', 'Kuria East', 'Kuria West', 'Mabera', 'Ntimaru', 'Rongo', 'Suna East', 'Suna West', 'Uriri']},
        {'county_name': 'Mombasa', 'subcounties': ['Changamwe', 'Jomvu', 'Kisauni', 'Likoni', 'Mvita', 'Nyali']},
        {'county_name': 'Muranga', 'subcounties': ['Gatanga', 'Kahuro', 'Kandara', 'Kangema', 'Kigumo', 'Kiharu', 'Mathioya', 'Murang\'a South']},
        {'county_name': 'Nairobi', 'subcounties': ['Dagoretti North', 'Dagoretti South', 'Embakasi Central', 'Embakasi East', 'Embakasi North', 'Embakasi South', 'Embakasi West', 'Kamukunji', 'Kasarani', 'Kibra', 'Lang\'ata', 'Makadara', 'Mathare', 'Roysambu', 'Ruaraka', 'Starehe', 'Westlands']},
        {'county_name': 'Nakuru', 'subcounties': ['Bahati', 'Gilgil', 'Kuresoi North', 'Kuresoi South', 'Molo', 'Naivasha', 'Nakuru Town East', 'Nakuru Town West', 'Njoro', 'Rongai', 'Subukia']},
        {'county_name': 'Nandi', 'subcounties': ['Aldai', 'Chesumei', 'Emgwen', 'Mosop', 'Nandi Hills', 'Tindiret']},
        {'county_name': 'Narok', 'subcounties': ['Narok East', 'Narok North', 'Narok South', 'Narok West', 'Transmara East', 'Transmara West']},
        {'county_name': 'Nyamira', 'subcounties': ['Borabu', 'Manga', 'Masaba North', 'Nyamira North', 'Nyamira South']},
        {'county_name': 'Nyandarua', 'subcounties': ['Kinangop', 'Kipipiri', 'Ndaragwa', 'Ol-Kalou', 'Ol Joro Orok']},
        {'county_name': 'Nyeri', 'subcounties': ['Kieni East', 'Kieni West', 'Mathira East', 'Mathira West', 'Mukurweini', 'Nyeri Town', 'Othaya', 'Tetu']},
        {'county_name': 'Samburu', 'subcounties': ['Samburu East', 'Samburu North', 'Samburu West']},
        {'county_name': 'Siaya', 'subcounties': ['Alego Usonga', 'Bondo', 'Gem', 'Rarieda', 'Ugenya', 'Unguja']},
        {'county_name': 'Taita-Taveta', 'subcounties': ['Mwatate', 'Taveta', 'Voi', 'Wundanyi']},
        {'county_name': 'Tana River', 'subcounties': ['Bura', 'Galole', 'Garsen']},
        {'county_name': 'Tharaka-Nithi', 'subcounties': ['Tharaka North', 'Tharaka South', 'Chuka', 'Igambango’mbe', 'Maara', 'Chiakariga', 'Muthambi']},
        {'county_name': 'Trans-Nzoia', 'subcounties': ['Cherangany', 'Endebess', 'Kiminini', 'Kwanza', 'Saboti']},
        {'county_name': 'Turkana', 'subcounties': ['Loima', 'Turkana Central', 'Turkana East', 'Turkana North', 'Turkana South']},
        {'county_name': 'Uasin Gishu', 'subcounties': ['Ainabkoi', 'Kapseret', 'Kesses', 'Moiben', 'Soy', 'Turbo']},
        {'county_name': 'Vihiga', 'subcounties': ['Emuhaya', 'Hamisi', 'Luanda', 'Sabatia', 'Vihiga']},
        {'county_name': 'Wajir', 'subcounties': ['Eldas', 'Tarbaj', 'Wajir East', 'Wajir North', 'Wajir South', 'Wajir West']},
        {'county_name': 'West Pokot', 'subcounties': ['Central Pokot', 'North Pokot', 'Pokot South', 'West Pokot']},
    ]

    for item in data:
        county = County.objects.create(county_name=item['county_name'])
        for subcounty_name in item['subcounties']:
            SubCounty.objects.create(county=county, subcounty_name=subcounty_name)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_county_subcounty'),
    ]

    operations = [
        migrations.RunPython(seed_counties_and_subcounties),
    ]
