# Generated by Django 4.2.10 on 2024-03-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='unassigned', max_length=50),
        ),
    ]
