# Generated by Django 4.2.10 on 2024-03-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
