# Generated by Django 4.2.10 on 2024-02-25 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0004_auto_20240224_2153'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('farm_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('product_image1', models.ImageField(upload_to='images/')),
                ('product_image2', models.ImageField(upload_to='images/')),
                ('quantity_available', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location_county_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.county')),
                ('location_subcounty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subcounty')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
